[package]
name = "idle_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27.2"
serde_json = "1.0"
serde = "1.0"
event_forge = { git = "https://github.com/Krayt78/event_forge.git" }
